version: '3.5'

services:
  dynamodb:
    container_name: app-dynamodb
    image: amazon/dynamodb-local
    working_dir: /home/dynamodblocal
    networks:
      - backend
    ports:
      - '8000:8000'
  dynamodb-migrator:
    image: amazon/aws-cli:2.13.15
    container_name: app-dynamodb-migrator
    working_dir: /home/dynamodblocal
    command: dynamodb create-table --cli-input-json file://birthday.json --endpoint-url http://dynamodb:8000 --region us-east-1
    volumes:
      - ./schema:/home/dynamodblocal
    environment:
      - AWS_ACCESS_KEY_ID=dummykey
      - AWS_SECRET_ACCESS_KEY=dummysecret
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      - dynamodb
    networks:
      - backend
  dynamodb_admin:
    image: aaronshaf/dynamodb-admin:4.6.1
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000
      - AWS_ACCESS_KEY_ID=dummykey
      - AWS_SECRET_ACCESS_KEY=dummysecret
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      - dynamodb
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    name: sam-app-network
